name: Test Examples
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linting:
    name: Lint all the Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install Root Dependencies
        run: yarn install
      - name: Run Linting
        run: yarn lint
  test-example:
    name: Test Example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [basic, basic-cdn, basic-ts, basic-sass-custom-theming, basic-react-router, parcel, parcel-ts]
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v1
      - name: Install Dependencies
        working-directory: ${{ matrix.dir }}
        run: yarn install
      - name: Run Tests
        env:
          CI: true
        working-directory: ${{ matrix.dir }}
        run: yarn test
      - name: Build project
        run: yarn build
        working-directory: ${{ matrix.dir }}
